name: Make Debian Package

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*-deb"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Building preparation
      run: |
        sudo apt install -y cmake
        sudo apt install -y g++
        sudo apt install -y clang

    - name: Build Solver App and Create Debian Package
      run: |
        mkdir build
        cd build
        cmake ..
        make
        cpack -G DEB packages
        cpack -G ZIP packages
        cpack -G TGZ packages

#    - name: Create Release
#      id: create_release
#      uses: actions/create-release@v1
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
#      with:
#        tag_name: ${{ github.ref }}
#        release_name: Release ${{ github.ref }}
#        body: build/packages/*

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          build/packages/*.deb
          build/packages/*.tar.gz
          build/packages/*.zip
      id: "automatic_release"

    - name: Set release tag
    run: echo "::set-output name=release_tag::${{ steps.create_release.outputs.tag_name }}"
    id: "automatic_release_tag"
