name: Make Debian Package

on:
  push:
    tags:
      - "v*.*.*-dmb"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Building preparation
        run: sudo apt install -y cmake g++ cpack clang

      - name: Build Solver App and Create Debian Package
        run: |
          mkdir build
          cd build
          cmake ..
          cpack -G DMB -G ZIP -G TGZ packages

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            build/packages/*.dmb
            build/packages/*.tar.gz
            build/packages/*.zip
        id: "automatic_releases"