name: Make Red Hat Package Manager Package

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*-rpm"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Building preparation
        run: |
          sudo apt install -y cmake
          sudo apt install -y g++
          sudo apt install -y clang

      - name: Build Solver App and Create Red Hat Package Manager Package
        run: |
          mkdir build
          cd build
          cmake ..
          make package
          make package_source

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN }}"
          prerelease: false
          files: |
            build/*.rpm
            build/*.tar.gz
            build/*.zip
        id: "automatic_release"

      - name: Set release tag
        run: echo "::set-output name=release_tag::${{ steps.create_release.outputs.tag_name }}"
        id: "automatic_release_tag"