name: Make Debian Package

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*-deb"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Building preparation
      run: |
        sudo apt install -y cmake
        sudo apt install -y g++
        sudo apt install -y clang

    - name: Build Solver App and Create Debian Package
      run: |
        mkdir build
        cd build
        cmake ..
        make
        cpack -G DEB
        cpack -G ZIP
        cpack -G TGZ

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.TOKEN }}"
        prerelease: false
        files: build/*
      id: "automatic_release"

    - name: Set release tag
      run: echo "::set-output name=release_tag::${{ steps.create_release.outputs.tag_name }}"
      id: "automatic_release_tag"
