name: Make DragNDrop Package

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*-dmb"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Building preparation
        run: |
          sudo apt install -y cmake
          sudo apt install -y g++
          sudo apt install -y clang

      - name: Build Solver App and Create DragNDrop Package
        run: |
          mkdir build
          cd build
          cmake ..
          make
          cpack -G DragNDrop
          cpack -G ZIP
          cpack -G TGZ

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN }}"
          prerelease: false
          files: |
            build/packages/*.dmb
            build/packages/*.tar.gz
            build/packages/*.zip
        id: "automatic_release"