name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*-debian"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
    - uses: actions/checkout@v3

    - name: preparation
      run: sudo apt install -y cmake g++ cpack clang
          
    - name: Build Solver_app with Debian Generator
      run: |
        mkdir solver_application/build
        cd solver_application/build
        cmake CPACK_GENERATOR_DEB=ON ..
        make package
        make package_source
        cd ..
        mkdir artifacts
        mv build/*.deb artifacts
        mv build/*.zip artifacts
        mv build/*.tar.gz artifacts

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: solver_application/artifacts/*
